site_name: Anaplan SDK
site_description: Provides pythonic access to the Anaplan API.
site_url: https://vinzenzklass.github.io/anaplan-sdk/

theme:
  name: 'material'
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'dark blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'

repo_name: VinzenzKlass/anaplan-sdk
repo_url: https://github.com/VinzenzKlass/anaplan-sdk

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Quick Start: 'quickstart.md'
  - Anaplan Explained: 'anaplan_explained.md'
  - Guides:
      - Logging: 'logging.md'
  - API Reference:
      - Developer Interface: 'api.md'
      - Models: 'models.md'
      - Exceptions: 'exceptions.md'


markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
