site_name: Anaplan SDK
site_description: Provides pythonic access to the Anaplan API.
site_url: https://vinzenzklass.github.io/anaplan-sdk/

theme:
  name: 'material'
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'dark blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - content.code.copy

repo_name: VinzenzKlass/anaplan-sdk
repo_url: https://github.com/VinzenzKlass/anaplan-sdk

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Quick Start: 'quickstart.md'
  - Anaplan Explained: 'anaplan_explained.md'
  - Guides:
      - Use the Bulk API: 'bulk.md'
      - Use the Transactional API: 'transactional.md'
      - Logging: 'logging.md'
  - API Reference:
      - Developer Interface:
          - AsyncClient: 'async_client.md'
          - Client: 'client.md'
          - Async Transactional Client: 'async_transactional_client.md'
          - Transactional Client: 'transactional_client.md'
      - Models: 'models.md'
      - Exceptions: 'exceptions.md'


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
            docstring_style: "sphinx"
            show_source: false
            show_bases: false


markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
